services:
  - type: redis
    name: private redis
    ipAllowList: []
    plan: free
  - type: web
    name: next-js
    env: node
    plan: starter
    buildCommand: yarn; yarn build
    startCommand: yarn start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
    key: REDIS_URL
    fromService:
      type: redis
      name: private redis
      property: connectionString
    