databases:
  - name: private database
    databaseName: private database
    user: postgres
    plan: free
    ipAllowList: []

services:
  - type: redis
    name: private redis
    ipAllowList: []
    plan: free
  - type: pserv
    name: pgbouncer
    runtime: docker
    plan: free
    repo: https://github.com/render-oss/docker-pgbouncer
    envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: private database
        property: connectionString
    - key: POOL_MODE
      value: transaction
    - key: SERVER_RESET_QUERY
      value: DISCARD ALL
    - key: MAX_CLIENT_CONN
      value: 500
    - key: DEFAULT_POOL_SIZE
      value: 50
  - type: web
    name: next-js
    env: node
    plan: free
    buildCommand: yarn; yarn build
    startCommand: yarn migrate; yarn start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: private redis
          property: connectionString
      - key: DATABASE_URL
        fromService:
          name: pgbouncer
          property: connectionString